/*me : "HelloWorld.java". */
class HelloWorld
{
	    // Your program begins with a call to main().
	    //     // Prints "Hello, World" to the terminal window.
	    //         public static void main(String args[])
	    //             {
	    //                     System.out.println("Hello, World");
	    //                         }
	    //                         /* This is a simple Java program.
	    //                            FileName : "HelloWorld.java". */
	    //                            class HelloWorld
	    //                            {
	    //                                // Your program begins with a call to main().
	    //                                    // Prints "Hello, World" to the terminal window.
	    //                                        public static void main(String args[])
	    //                                            {
	    //                                                    System.out.println("Hello, World");
	    //                                                        }
	    //                                                        }
	    //
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                        ~
	    //                                                                                                                                                                                                                  22,0-1        All
	    //                                                                                                                                                                                                                  qa!This is a simple Java program.
   FileName : "HelloWorld.java". */
class HelloWorld
{
    // Your program begins with a call to main().
    // Prints "Hello, World" to the terminal window.
    public static void main(String args[])
    {
        System.out.println("Hello, World");
    }
/* This is a simple Java program.
   FileName : "HelloWorld.java". */
class HelloWorld
{
    // Your program begins with a call to main().
    // Prints "Hello, World" to the terminal window.
    public static void main(String args[])
    {
        System.out.println("Hello, World");
    }
}
/* This is a simple Java program.
   FileName : "HelloWorld.java". */
class HelloWorld
{
    // Your program begins with a call to main().
    // Prints "Hello, World" to the terminal window.
    public static void main(String args[])
    {
        System.out.println("Hello, World");
    }
/* This is a simple Java program.
   FileName : "HelloWorld.java". */
class HelloWorld
{
    // Your program begins with a call to main().
    // Prints "Hello, World" to the terminal window.
    public static void main(String args[])
    {
        System.out.println("Hello, World");
    }
}

~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
                                                                                                                                                          22,0-1        All
/*me : "HelloWorld.java". */
																			  class HelloWorld
{
	            // Your program begins with a call to main().
		    //             //     // Prints "Hello, World" to the terminal window.
		    //                         //         public static void main(String args[])
		    //                                     //             {
		    //                                                 //                     System.out.println("Hello, World");
		    //                                                             //                         }
		    //                                                                         //                         /* This is a simple Java program.
		    //                                                                                     //                            FileName : "HelloWorld.java". */
		    //                                                                                                 //                            class HelloWorld
		    //                                                                                                             //                            {
		    //                                                                                                                         //                                // Your program begins with a call to main().
		    //                                                                                                                                     //                                    // Prints "Hello, World" to the terminal window.
		    //                                                                                                                                                 //                                        public static void main(String args[])
		    //                                                                                                                                                             //                                            {
		    //                                                                                                                                                                         //                                                    System.out.println("Hello, World");
		    //                                                                                                                                                                                     //                                                        }
		    //                                                                                                                                                                                                 //                                                        }
		    //                                                                                                                                                                                                             //
		    //                                                                                                                                                                                                                         //                                                        ~
		    //                                                                                                                                                                                                                                     //                                                        ~
		    //                                                                                                                                                                                                                                                 //                                                        ~
		    //                                                                                                                                                                                                                                                             //                                                        ~
		    //                                                                                                                                                                                                                                                                         //                                                        ~
		    //                                                                                                                                                                                                                                                                                     //                                                        ~
		    //                                                                                                                                                                                                                                                                                                 //                                                        ~
		    //                                                                                                                                                                                                                                                                                                             //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                         //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                     //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                 //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                             //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                         //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                                     //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                 //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                             //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                         //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                     //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                 //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                             //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     //                                                        ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 //                                                                                                                                                                                                                  22,0-1        All
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             //                                                                                                                                                                                                                  qa!This is a simple Java program.
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                FileName : "HelloWorld.java". */
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                class HelloWorld
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Your program begins with a call to main().
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Prints "Hello, World" to the terminal window.
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        -- INSERT --                                                                                                                                              49,221-228    10%
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        class HelloWorld
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Your program begins with a call to main().
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Prints "Hello, World" to the terminal window.
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    public static void main(String args[])
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                System.out.println("Hello, World");
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    /* This is a simple Java program.
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       FileName : "HelloWorld.java". */
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       class HelloWorld
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           // Your program begins with a call to main().
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               // Prints "Hello, World" to the terminal window.
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   public static void main(String args[])
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               System.out.println("Hello, World");
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   }
		    //
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ~
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             22,0-1        All
		    //
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             -- INSERT --                                                                                                                                              119,1         Bot
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           qa!
		    //                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           !qa
		    //                                                                                                                            !
		    //!
		    //
